name: Publish Docker Image To Github Registry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/spuute/test
          tag-sha: true
          tag-edge: false
          tag-latest: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
        
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
